OK = 0
# SYSTEM ERROR

# REQUEST INVALID
BAD_REQUEST = 10
NO_SELECTED_FILE = 11
UNSUPPORTED_FILE_TYPE = 12

# BUSINESS ERROR
INVALID_DATASET = 100
MISMATCH_DATASET = 101
INVALID_SWAP_TEST = 102
COMPARATION_GROUP_ALREADY_EXISTS = 103
COMPARATION_GROUP_NOT_EXIST = 104
INVALID_SCORE = 105
COMPARATION_RESULT_NOT_EXIST = 106
COMPARATION_RESULT_DATA_COUNT_NOT_RIGHT = 107
INVALID_FACE = 108
INVALID_FACE_GROUP = 109
FACE_GROUP_LOCKED = 110

# MIDWARE ERROR
DB_FAILED_TO_SAVE = 1000

CODE_MSG = {
    OK: "OK",

    BAD_REQUEST: "错误请求",
    NO_SELECTED_FILE: "没有选择文件",
    UNSUPPORTED_FILE_TYPE: "不支持的文件类型",

    INVALID_DATASET: "非法数据集",
    MISMATCH_DATASET: "数据集不匹配",
    INVALID_SWAP_TEST: "非法的换脸测试结果",
    COMPARATION_GROUP_ALREADY_EXISTS: "对照组已经存在",
    COMPARATION_GROUP_NOT_EXIST: "对照组不存在",
    INVALID_SCORE: "非法评分",
    COMPARATION_RESULT_NOT_EXIST: "评比结果不存在",
    COMPARATION_RESULT_DATA_COUNT_NOT_RIGHT: "对比结果的个数不一致",
    INVALID_FACE: "人脸非法",
    INVALID_FACE_GROUP: "非法人脸组",

    DB_FAILED_TO_SAVE: "保存至数据库失败"

}
