OK = 0
INVALID_DATASET = 100
MISMATCH_DATASET = 101
INVALID_SWAP_TEST = 102
COMPARATION_GROUP_ALREADY_EXISTS = 103
COMPARATION_GROUP_NOT_EXIST = 104
INVALID_SCORE = 105
COMPARATION_RESULT_NOT_EXIST = 106
COMPARATION_RESULT_DATA_COUNT_NOT_RIGHT = 107
DB_FAILED_TO_SAVE = 1000

CODE_MSG = {
    OK: "OK",
    INVALID_DATASET: "非法数据集",
    MISMATCH_DATASET: "数据集不匹配",
    INVALID_SWAP_TEST: "非法的换脸测试结果",
    COMPARATION_GROUP_ALREADY_EXISTS: "对照组已经存在",
    COMPARATION_GROUP_NOT_EXIST: "对照组不存在",
    INVALID_SCORE: "非法评分",
    COMPARATION_RESULT_NOT_EXIST: "评比结果不存在",
    DB_FAILED_TO_SAVE: "保存至数据库失败",
    COMPARATION_RESULT_DATA_COUNT_NOT_RIGHT: "对比结果的个数不一致"
}
